### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jdtaylor7** [textshell/stm32-from-scratch#1]
Hello @textshell, would you mind adding a [license](https://choosealicense.com/) to the repo? If you want to minimize restrictions and keep things simple I would suggest the MIT license.

**Comment by textshell** [comment]
Sorry for the delayed response.

I guess in never considered much of this as reusable, except the linker script which has a license. But i guess i should add a license for the rest as well.
I've now added a COPYING file with the 0BSD license which should solve this.
